version: "3.1"

services:
  db_gym_one:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: vinicius
      POSTGRES_PASSWORD: £ukH`6C7k2
      POSTGRES_DB: gymone
    volumes:
      - gym_one_pg_data:/postgres
    ports:
      - "5432:5432"

volumes:
  gym_one_pg_data:
